# Generated by Django 6.1.1 on 2026-09-25 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desk_number",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Номер стола",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочее место",
                "verbose_name_plural": "Рабочие места",
                "ordering": ["desk_number"],
            },
        ),
    ]
