# Generated by Django 6.1.1 on 2026-09-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employeeimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата приёма на работу"
            ),
        ),
    ]
